### ISSUE TITLE
Feature Request: Change Main Product Image on Admin Page

### ISSUE THREAD

**Issue by dsanders11** [stephenmcd/cartridge#158]
Currently there is no way to easily change the image for a product with variations on the admin page.

For example, I created a product with several color variations, and marked one of the colors as the default.

However, I'd like to display a different image (an image with all color variants shown) as the main image for the product.

Manually changing the image field on shop_product accomplishes this, displaying the correct image as the main image in the category view (although the product view seems to select the default product as the main image on that page).

Changes to the product page reset this though, hence the request for an option on the admin page to make it easier.

It seems to me that there's a possible improvement here:
* Change the image field on shop.Product to be a foreign key to shop.ProductImage like it is on shop.ProductVariation
* Add it as an admin field for shop.Product
* Some kind of option to have no default variant? The variant drop down box could say "Please Select" and the main image would be displayed until a variant is selected at which point the variant image would be displayed.

**Comment by stephenmcd** [comment]
Don't think the user should have to deal with this unless you have a specific case for it like yours - in which case I'd recommend replacing the admin class with your own subclass.
