### ISSUE TITLE
Download PDF generates Import Error: Reportlab Version 2.1+ is needed!

### ISSUE THREAD

**Issue by mcchan1** [stephenmcd/cartridge#174]
Hi, 

I'm a Django noob, and I'm generally out of my league when it comes to dependency issues.  Thanks in advance for your help! 

When I try to generate a PDF of the invoice, I receive this error: 

"Reportlab Version 2.1+ is needed!"

  I have Reportlab 3.0 installed.

I'm working in a clean virtualenv.  This is my pip freeze:

Cartridge==0.9.2
Django==1.6.2
Drum==0.1.2
Mezzanine==3.0.9
PIL==1.1.7
Pillow==2.3.0
bleach==1.4
feedparser==5.1.3
filebrowser-safe==0.3.2
future==0.9.0
grappelli-safe==0.3.6
html5lib==1.0b3
oauthlib==0.6.1
pisa==3.0.33
pyPdf==1.13
pytz==2013.9
reportlab==3.0
requests==2.2.1
requests-oauthlib==0.4.0
six==1.5.2
sphinx-me==0.2.1
tzlocal==1.0
wsgiref==0.1.2
xhtml2pdf==0.0.5

**Comment by rajanmandanka** [comment]
Option 1 : 

Remove below in your requirements.txt file
pisa==x.x.xx

and add:

-e git+https://github.com/rajanmandanka/pisa.git#egg=pisa

Option 2:

1. uninstall pisa
pip uninstall pisa

2. install pisa using pip
pip install git+https://github.com/rajanmandanka/pisa.git

**Comment by jerivas** [comment]
Could you elaborate a bit? Which versions of Python / Django / Mezzanine 
/ Cartridge are you using? Can you provide a reproducible test case?

**Comment by rajanmandanka** [comment]
I am using 
python 2.7
Django 1.8

I have tested this with python3 too and its working fine

**Comment by andreipradan** [comment]
git+https://github.com/rajanmandanka/pisa.git#egg=pisa not found anymore
