### ISSUE TITLE
select_related does not take a depth argument in Django 1.7

### ISSUE THREAD

**Issue by ghost** [stephenmcd/cartridge#211]
See Release Notes:

http://django.readthedocs.org/en/latest/releases/1.7.html#features-removed-in-1-7

This causes the shop checkout to fail at the "confirm order" stage.

**Comment by qcaron** [comment]
Hi guys,

I still encounter this 'depth' problem with Django 1.7. I tried the following without success to update the package code: 
```
pip install -U --no-deps --pre cartridge
```

My guess is that the code has not been released to PyPI, am I correct? If yes, by any chance, do you plan do it soon? If no, how could I figure this out?

Thank you very much!!!
Quentin

**Comment by AlexHill** [comment]
Hi Quentin, that's right – the current versions of Mezzanine and Cartridge don't support Django 1.7. The release currently in the works will most likely jump straight to 1.8.

**Comment by qcaron** [comment]
That's a shame :( So far, everything's working fine with Django 1.7 for me. The only problem being that *depth* parameter in select_related. 
So no chance you release the current version on PyPI? 0:-)

**Comment by AlexHill** [comment]
You can install the development versions with pip like this:

``pip install https://github.com/stephenmcd/mezzanine/archive/master.zip``

and 

``pip install https://github.com/stephenmcd/cartridge/archive/master.zip``

**Comment by qcaron** [comment]
I managed to update packages and the shop looks good. Thank you very much Alex!
