### ISSUE TITLE
Resending invoice emails broken

### ISSUE THREAD

**Issue by molokov** [stephenmcd/cartridge#225]
I've been getting the following error when trying to resend an invoice email from either account/orders or the admin.

    Traceback (most recent call last):

     File '.../lib/python2.7/site-packages/django/core/handlers/base.py', line 105, in get_response
       response = middleware_method(request, callback, callback_args, callback_kwargs)
     File '.../lib/python2.7/site-packages/mezzanine/pages/middleware.py', line 103, in process_view
       return view_func(request, *view_args, **view_kwargs)
     File '.../lib/python2.7/site-packages/django/contrib/auth/decorators.py', line 22, in _wrapped_view
       return view_func(request, *args, **kwargs)
     File '.../cartridge/shop/views.py', line 443, in invoice_resend_email
       return redirect(redirect_to)
    UnboundLocalError: local variable 'redirect_to' referenced before assignment

I suspect somehow we're getting into this function with request.method == "GET", and thus the return statement in the function 'invoice_resend_email' isn't valid.

**Comment by stephenmcd** [comment]
You're right, and I'll update the view function to be more correct - but I think this was resolved at the template level some time ago, so I suggest you're missing those changes.

**Comment by stephenmcd** [comment]
Thanks for the report BTW!
