### ISSUE TITLE
Country as select to better handle included taxes

### ISSUE THREAD

**Issue by qcaron** [stephenmcd/cartridge#234]
Hi guys ! 

I am working on a shop for a French company and have some troubles with taxes.

French prices already include VAT, so I do not use the *SHOP_HANDLER_TAX* here. Instead, as the [documentation] (http://cartridge.jupo.org/integration.html?highlight=country#tax) states it, I made changes to *shop/includes/order_details.html* and *shop/includes/order_totals.html*. My changes use an inclusion tag which renders (or not) a new line for the included taxes such as this after the *Order total* line:

```
TVA : 19 Eu (20,0%)
```

In the templates I test the country using *request.session.order.billing_detail_order* which comes from *OrderForm.fields['billing_detail_country']*. *OrderForm* being a *ModelForm* using Order as Meta class, the country field is a *CharField*.
As you can imagine, a user giving a bad country such as "Frznce" instead of "France" will just ruin the test and the included taxes display will be missing. Why not making the country field's widget a Select ?

Maybe [django-countries] (https://github.com/SmileyChris/django-countries/) could be used for this ?

Thanks for your feedback! If you would be happy with this kind of update, I can make a pull request ;)

Cheers!
Quentin

---------

As of today, here is my full code. It may help you in understanding my work. Who knows, this may even be interesting for future improvements of Cartridge :)

My inclusion tag *included_taxes* looks like this :
```python
@register.inclusion_tag('shop/includes/included_taxes.html')
def included_taxes(order_total, country):
    """
    Show the tax amount for display purposes when the price already includes taxes.
    This happens for France for example.
    :param order_total: the order total amount
    :param country: country used for billing
    :return: a dictionary with the following keys:
        - tax_name : the name of the tax
        - tax_total: the tax_total according the
    """
    country = country.lower()
    inclusion_context = {
        'included_tax_display': tax_included_display(country),
        'included_tax_name': 'Tax',  # Dummy name just as the tax_handler would
        'included_tax_total': 0,
        'included_tax_rate_as_percentage': 0,
    }

    if country == COUNTRY_FRANCE:
        tax_rate = 0.2

        inclusion_context['included_tax_name'] = 'TVA'
        inclusion_context['included_tax_total'] =
            (order_total * decimal.Decimal(1 + tax_rate)) - order_total
        inclusion_context['included_tax_rate_as_percentage'] = tax_rate * 100

    return inclusion_context
```

*tax_included_display* assignment tag :
```python
@register.assignment_tag()
def tax_included_display(country):
    country = country.lower()
    if country in COUNTRIES_INCLUDING_TAXES:
        return True
    return False
```

*shop/includes/order_totals.html* looks like this :
```html
{% tax_included_display request.session.order.billing_detail_country as country_has_included_taxes %}
    {% if not country_has_included_taxes and tax_total %}
        <div>
            <label>
                {% if tax_type %}
                    {{ tax_type }} :
                {% else %}
                    {% trans "Tax" %} :
                {% endif %}
            </label>
            <span>{{ tax_total|currency }}</span>
        </div>
    {% endif %}

    <div class="total">
        <label>
            {% trans "Total" %} :
        </label>
        <span>
            {{ order_total|currency }}
        </span>
    </div>

    {% included_taxes order_total request.session.order.billing_detail_country %}
```

and finally *shop/includes/included_taxes.html*:
```html
{% load shop_tags %}
{% if included_tax_is_displayed %}
    <br>
    <div class="included-taxes">
        <label>
            {{ included_tax_name }} :
        </label>
        <span>
            {{ included_tax_total|currency }} ({{ included_tax_rate_as_percentage }}%)
        </span>
    </div>
{% endif %}
```

**Comment by stephenmcd** [comment]
Building in country specific logic into Cartridge is really beyond what I think its scope is, so I don't think this belongs inside Cartridge. It looks like you've been able to implement what you need, which is awesome - as far as reusability goes, perhaps you could wrap it up into a separate app and make that available.

Thanks

**Comment by qcaron** [comment]
Thanks for your feedback Stephen! I will continue working on this. Maybe my first Django app :)
If anyone is interested in such an app please let me know!!
