### ISSUE TITLE
Checkout form : data from other user

### ISSUE THREAD

**Issue by qcaron** [stephenmcd/cartridge#236]
Hello !

I am working with the bleeding edge version master.zip (OK I know, probably not the best idea but I needed the latest Django 1.7.x version).
I have deployed in a test environment and made some purchases. I have checked "remember me" to avoid typing my billing details again. It works fine for me, but another user (using another computer in another network) who made a purchase got a billing form filled with my details (name, address on the OrderForm first step).

Is it a configuration problem in my test env or a cartridge bug ?

**Comment by stephenmcd** [comment]
Did you both access the admin area with the same login?

**Comment by qcaron** [comment]
No an admin/staff user cannot make a purchase. We both used different accounts.

**Comment by stephenmcd** [comment]
Well that's the only explanation unfortunately.

**Comment by qcaron** [comment]
Wow... okay ^^ Maybe I can have a deeper look in DB or anything else related to my test env. Where are the "remembered" billing details coming from ?

**Comment by stephenmcd** [comment]
The code's here:

https://github.com/stephenmcd/cartridge/blob/master/cartridge/shop/checkout.py#L79

It basically looks up user ID for the logged in used (which is what I think you're seeing), or if not logged in, it looks for a key in the user's cookie, which is also stored against orders.

**Comment by stephenmcd** [comment]
BTW please report back what you find - I'm fairly confident you've used the same login somehow, or there's possibly some HTTP caching issue in your test environment, but honestly there's nothing to go on here unless you can provide steps to reproduce this - I've tried and it works as expected, so I'll close this for now.

**Comment by qcaron** [comment]
Thank you Stephen. I will let you know if I find anything !
