### ISSUE TITLE
Extending cartridge orders to be real time.

### ISSUE THREAD

**Issue by andrewfam** [stephenmcd/cartridge#239]
I'm  using cartridge but the customer wants a real time update page of all orders coming in.
Thinking of swampdragon as per this link http://swampdragon.net/documentation/quick-start/

from django.db import models
from swampdragon.models import SelfPublishModel
from .serializers import FooSerializer

class Foo(SelfPublishModel, models.Model):
    serializer_class = FooSerializer
    text = models.CharField(max_length=100)

The first line that defines the class includes the SelfPublishModel which highlights its in real time. Any idea of how i can fork or extend the Order object to include this?

**Comment by stephenmcd** [comment]
Hi,

Thanks for the link. I don't think this warrants opening an issue here. There's certainly nothing in Cartridge stopping you from working with websockets.

If you'd like to discuss it further, please send an email to the mailing list.
