### ISSUE TITLE
New cartridge project throwing error on FileSystemStorage

### ISSUE THREAD

**Issue by dinopetrone** [stephenmcd/cartridge#247]
'FileSystemStorage' object has no attribute 'isdir'

Full description here:
https://gist.github.com/dinopetrone/19d5fc2af788fc6cb9e2

**Comment by stephenmcd** [comment]
Thanks for the detail - it looks like you're using a custom storage backend `require.storage.OptimizedStaticFilesStorage` that doesn't implement `isdir`.

**Comment by dinopetrone** [comment]
Praying i'm not doing something epic'ly stupid here..same error but with backend switched out

https://gist.github.com/dinopetrone/14001d2c7cd975f3944f

**Comment by Kniyl** [comment]
This one does not implement ```isdir``` either. ```makedirs``` will also be needed. You could get started with:
```python
class MyFileSystemStorage(django.contrib.staticfiles.storage.StaticFilesStorage):
    def isdir(self, path):
        return os.path.isdir(path)
    def makedirs(self,path):
        os.makedirs(path)
```

**Comment by stephenmcd** [comment]
We might need to fix this in Mezzanine (filebrowser-safe actually) since the error's now occurring with one of Django's built-in backends.

**Comment by stephenmcd** [comment]
Actually the storage backend you have configured in your latest error looks fine - but you don't have filebrowser_safe in `INSTALLED_APPS` - that should happen automatically if you install everything according to the docs.

**Comment by dinopetrone** [comment]
@stephenmcd well played sir...sorry for the false alarm.  Adding that got everything up and running.  I was porting over your django template to the one we use and your installed apps doesn't have filebrowser_safe in it.  You must be doing it via some magic elsewhere.  Thanks for the help!

**Comment by stephenmcd** [comment]
Awesome! Glad it's sorted.
