### ISSUE TITLE
mezzanine-project mezzanine_project: error: unrecognized arguments: -a

### ISSUE THREAD

**Issue by n1ywb** [stephenmcd/cartridge#257]
Trying to use cartridge master with Mezzanine master and django 1.8, I get the following error when I try to create the cartridge project

```bash
$ mkvirtualenv mezmaster
$ pip install git+https://github.com/stephenmcd/mezzanine.git#egg=mezzanine
$ pip install git+https://github.com/stephenmcd/cartridge.git#egg=cartridge
$ mezzanine-project -a cartridge localvore-dev
usage: mezzanine-project mezzanine_project [-h] [--version] [-v {0,1,2,3}]
                                           [--settings SETTINGS]
                                           [--pythonpath PYTHONPATH]
                                           [--traceback] [--no-color]
                                           [--template TEMPLATE]
                                           [--extension EXTENSIONS]
                                           [--name FILES]
                                           name [directory]
mezzanine-project mezzanine_project: error: unrecognized arguments: -a
```

installed packages
```bash
$ pip freeze
Cartridge==0.9.5
Django==1.8.2
Mezzanine==3.1.10
Pillow==2.8.2
PyPDF2==1.24
argparse==1.2.1
beautifulsoup4==4.3.2
bleach==1.4.1
chardet==2.3.0
django-contrib-comments==1.6.1
filebrowser-safe==0.3.8
future==0.14.3
grappelli-safe==0.3.13
html5lib==0.99999
oauthlib==0.7.2
pytz==2015.4
reportlab==3.2.0
requests==2.7.0
requests-oauthlib==0.5.0
six==1.9.0
tzlocal==1.2
wsgiref==0.1.2
xhtml2pdf==0.0.6
```

Let me know if you need more info

**Comment by n1ywb** [comment]
I also tried 

```bash
$ mezzanine-project --template cartridge localvore-dev
CommandError: couldn't handle project template cartridge.
```

**Comment by Kniyl** [comment]
That is the consequence of a recent merge in mezzanine that changed the project layout to match django's one. Cartridge has still to catch up.

More information at https://groups.google.com/forum/m/#!topic/mezzanine-users/7bqDYtfCId8

**Comment by JamesRamm** [comment]
Any timescale on when this will be fixed? Currently, cartridge is essentially broken for clean installs and without trawling the internet to find hacks, making a new cartridge website is a no go. 

If you do this:

`mkvirtualenv mywebsite`
`pip install mezzanine cartridge`

You will end up with mezzanine 4.0, django 1.8 and cartridge 0.95. Attempting to make a new cartridge website will fail...

**Comment by ryneeverett** [comment]
The latest compatible releases seem to be `cartridge==0.9.3` and `mezzanine<4.0`.

**Comment by stephenmcd** [comment]
You can also use Mezzanine 4.0, Django 1.8 plus the development branch of Cartridge using these steps to start a project:

https://groups.google.com/d/msg/mezzanine-users/q8Cu1obn2BA/JyXCXCafwdQJ

**Comment by ryneeverett** [comment]
Thanks @stephenmcd, works beautifully and seems smarter for new projects.

**Comment by jayetan** [comment]
https://groups.google.com/d/msg/mezzanine-users/q8Cu1obn2BA/JyXCXCafwdQJ

this doesn't fixed the issue I got 
django.core.exceptions.ImproperlyConfigured: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is prohibited; form ProductAdminForm needs updating.

**Comment by stephenmcd** [comment]
> this doesn't fixed the issue I got 
> django.core.exceptions.ImproperlyConfigured: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is prohibited; form ProductAdminForm needs updating.

Sorry I don't think this is related.

Actual issue fixed by https://github.com/stephenmcd/mezzanine/commit/f3be54b88b3540576e46606385fb00b2e9877209 and https://github.com/stephenmcd/cartridge/commit/a0f2cd78b836dfe32f25bad434efdfe363092c8a

**Comment by rcarmo** [comment]
I'd like to keep this open until pip is updated, since I just came across the exact same issue with a fresh install and it's just nicer to new users...
