### ISSUE TITLE
 shipping_fields.js is broken starting from jquery 1.9

### ISSUE THREAD

**Issue by georgema1982** [stephenmcd/cartridge#258]
This script is not working under jquery 1.9+. I think it should be modified to work under latest jquery considering the fact that mezzanine uses bootstrap 3 which requires jquery 1.9+.

**Comment by georgema1982** [comment]
I find a workaround to resolve this issue without modifying the script. Add the below line to the template right after jquery reference:

<script src="http://code.jquery.com/jquery-migrate-1.2.1.js"></script>

But of course, this script still needs to be fixed in future release of cartridge.

**Comment by stephenmcd** [comment]
Great, could you create a pull request for the fix? Thanks!

**Comment by slav0nic** [comment]
check
```diff
@@ -6,7 +6,7 @@ $(function() {
 
     // show/hide shipping fields on change of "same as" checkbox and call on load
     sameShipping.change(function() {
-        $('#shipping_fields')[sameShipping.attr('checked') ? 'hide' : 'show']();
+        $('#shipping_fields')[sameShipping.prop('checked') ? 'hide' : 'show']();
     }).change();
 
 });
```

**Comment by stephenmcd** [comment]
Cool. Mind creating a PR? Thanks.
