### ISSUE TITLE
mezzanine-project mezzanine_project: error: unrecognized arguments: -a

### ISSUE THREAD

**Issue by aznnoh** [stephenmcd/cartridge#263]
Hi,

When I tried to start new project , I get this error:

(venv) C:\Users\John\Desktop\venv\shop>mezzanine-project -a cartridge newproject

usage: mezzanine-project mezzanine_project [-h] [--version] [-v {0,1,2,3}]
                                           [--settings SETTINGS]
                                           [--pythonpath PYTHONPATH]
                                           [--traceback] [--no-color]
                                           [--template TEMPLATE]
                                           [--extension EXTENSIONS]
                                           [--name FILES]
                                           name [directory]
mezzanine-project mezzanine_project: error: unrecognized arguments: -a

instaled packages in venv:

beautifulsoup4==4.4.0
bleach==1.4.1
Cartridge==0.9.5
chardet==2.3.0
Django==1.8.3
django-contrib-comments==1.6.1
filebrowser-safe==0.4.0
future==0.14.3
grappelli-safe==0.4.0
html5lib==0.999999
Mezzanine==4.0.0
oauthlib==1.0.0
Pillow==2.9.0
PyPDF2==1.25.1
pytz==2015.4
reportlab==3.2.0
requests==2.7.0
requests-oauthlib==0.5.0
six==1.9.0
tzlocal==1.2
xhtml2pdf==0.0.6

OS: WIN 7

**Comment by stephenmcd** [comment]
See #257
