### ISSUE TITLE
Digital/Downloadable Products.

### ISSUE THREAD

**Issue by certifiedloud** [stephenmcd/cartridge#270]
Is there any interest in a PR that implements digital products? To me it seems like a reasonable thing to include in the base features of cartridge.

**Comment by stephenmcd** [comment]
Been discussed many times on the mailing list before, which is where this question belongs:

https://groups.google.com/forum/#!searchin/mezzanine-users/downloadable

Consensus seems to be that it would be great to have this available as a separate app.
