### ISSUE TITLE
Reduce by amount discount not applied if amount exceeds item's unit_price 

### ISSUE THREAD

**Issue by twoblokeswithapostie** [stephenmcd/cartridge#283]
I ran into an issue where the discount amount is $150 and the item cost is $25. Even if the customer is purchasing 10 items, totalling at $250, the discount is not applied because def calculate(self, amount) inside DiscountCode model is returning 0.

I think the issue is caused by the following line 1043 inside def calculate_discount(self, discount): in the Cart model:

total += discount.calculate(item.unit_price) * item.quantity

I believe that this line should be changed to:

total += discount.calculate(item.unit_price * item.quantity)

I've made the change in my project and ran some tests and it works as it's supposed to on both types of discounts.

Any thoughts on this? I'm happy to submit a pull request if you thing there are no negative implications after this change...

**Comment by stephenmcd** [comment]
Discounts are per item, not order. If an order with 10 x $25 items should get a total discount of $150, the per-item discount that should be configured in the admin would be $15.
