### ISSUE TITLE
Easy settings for including shipping / tax / quantity?

### ISSUE THREAD

**Issue by geoffrey-eisenbarth** [stephenmcd/cartridge#292]
I'm using cartridge on a site that doesn't utilize shipping, tax, or quantity (electronic subscription), and am hoping to implement three boolean options into the settings for these situations today. Is there any interest in this? Or a way to do this already factored into the code? I know you can add custom shipping and tax calculation functions, but I don't see how those correspond with the presence of the fields in the various forms. 

Also, apologies if this is the wrong place to post this (is the Google Groups preferred?) I guess I figured I'd see if there was any interest before filing a pull request later.

**Comment by stephenmcd** [comment]
> Also, apologies if this is the wrong place to post this (is the Google Groups preferred?)

Yes, please post there.
