### ISSUE TITLE
Italian translation for State/Region

### ISSUE THREAD

**Issue by valholl** [stephenmcd/cartridge#300]
The italian translation of "State/Region" in `shop/locale/it/LC_MESSAGES/django.po` is "Stato/regione", which is correct, but a bit misguiding for Italian customers, since in that field they have to enter the "provincia" (province).

Could it be possible to translate it as just "Provincia" or "Provincia/stato"? I'd think the former is what Italian customers expect on an Italian website, while the latter is formally more correct in an international context.

(I'm afraid I don't have a transifex account to propose it directly on the translation website, sorry)

**Comment by stephenmcd** [comment]
No need to open an issue for this, please just create a pull request with the change.
