### ISSUE TITLE
Is there a way to import orders ?

### ISSUE THREAD

**Issue by tderouin** [stephenmcd/cartridge#315]
Is there a way to import orders from a different system using a utils script from the command line?

e.g.

```
cart = Cart()
product_variation = ProductVariation.objects.get(pk=id)
cart.add(production_variation)
order = Order(cart=cart, status=complete, user=user)
order.save() 
```

The Order.setup seems to rely on the request and request.session objects, but maybe there's a different way? 

Thanks! This is a great project.

**Comment by stephenmcd** [comment]
Again, please use the mailing list.
