### ISSUE TITLE
product_db breaks other django manage.py commands

### ISSUE THREAD

**Issue by rodney757** [stephenmcd/cartridge#323]
Django 1.10 removed the options_list of the BaseCommand class that product_db inherits.

When using Django 1.10 management commands from other apps, the product_db class throws a syntax error, preventing the use of custom django admin-commands.

#322 fixes this

**Comment by jerivas** [comment]
Thanks RJ. The pull request is enough for tracking this problem, no need to
open a separate issue.

Also, you don't need to open new PRs when you want to fix errors in your
forked branch. Just continue pushing to it and they'll show up as usual.
