### ISSUE TITLE
Translation into Spanish 

### ISSUE THREAD

**Issue by sleweddock** [stephenmcd/cartridge#328]
I want to translate this repo into spanish. I've already read the python documentation

I am opening this issue to let the owner and other translators that the spanish translation is ongoing. 

Hope to hear from you soon!

**Comment by kenbolton** [comment]
Looking at https://www.transifex.com/mezzanine/cartridge/, it appears the Spanish translation is complete.

**Comment by sleweddock** [comment]
Thanks for letting me know @kenbolton , will close the issue
