### ISSUE TITLE
Security concern

### ISSUE THREAD

**Issue by zidingz** [stephenmcd/cartridge#354]
Hey there!

I belong to an open source security research community, and a member (@ktg9) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by kenbolton** [comment]
https://github.com/stephenmcd/cartridge#support states:

> To report a security issue, please send an email privately to core-team@mezzaninecms.com. This gives us a chance to fix the issue and create an official release prior to the issue being made public.

**Comment by kenbolton** [comment]
FWIW, the reported security concern is mitigated by including`SESSION_COOKIE_SECURE = True` in settings.py. The issue was reported in the demo site.
